- name: Configure EC2 and install Docker
  hosts: web
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Update system packages
      dnf:
        name: "*"
        state: latest

    - name: Install required packages
      dnf:
        name:
          - docker
          - python3-pip
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Docker SDK for Python (safe method)
      pip:
        name: docker
        executable: pip3
        extra_args: --ignore-installed
    - name: Pull project from GitHub
      git:
        repo: https://github.com/Anly2004/devops-project.git
        dest: /home/ec2-user/devops-project

    - name: Build Docker image
      command: docker build -t mywebapp /home/ec2-user/devops-project

    - name: Stop old container
      command: docker stop mycontainer
      ignore_errors: yes

    - name: Remove old container
      command: docker rm mycontainer
      ignore_errors: yes

    - name: Run new container
      command: docker run -d -p 80:80 --name mycontainer mywebapp 
